// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBjKBO2hW2PW7QRuN4H8BYZOFSMWRA76E',
    appId: '1:256248141188:web:687ec88bdf0ffa140179d1',
    messagingSenderId: '256248141188',
    projectId: 'dse-elibrary-75930',
    authDomain: 'dse-elibrary-75930.firebaseapp.com',
    databaseURL: 'https://dse-elibrary-75930-default-rtdb.firebaseio.com',
    storageBucket: 'dse-elibrary-75930.firebasestorage.app',
    measurementId: 'G-3R9X25PGHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-gZFo0rL7RAKee2IwMiDHvHu_pQRU5gc',
    appId: '1:256248141188:android:837b59afef5876f70179d1',
    messagingSenderId: '256248141188',
    projectId: 'dse-elibrary-75930',
    storageBucket: 'dse-elibrary-75930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMkYHj6TjdCDHJRksQURq9H5qA4QYkFp0',
    appId: '1:256248141188:ios:bd0a9bd0b5a8536b0179d1',
    messagingSenderId: '256248141188',
    projectId: 'dse-elibrary-75930',
    databaseURL: 'https://dse-elibrary-75930-default-rtdb.firebaseio.com',
    storageBucket: 'dse-elibrary-75930.firebasestorage.app',
    iosClientId:
        '256248141188-43bi4tr032fnc9qd1sn4e7fktkcg1tl0.apps.googleusercontent.com',
    iosBundleId: 'com.systemsengineering.elibrary',
  );
}